sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11
  - DJANGO=2.1

matrix:
  fast_finish: true
  include:
    - python: "3.7-dev"
      env: DJANGO=2.1
    - python: "3.7-dev"
      env: DJANGO=2.1
  exclude:
    - python: "2.7"
      env: DJANGO=2.1

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
