sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
   allow_failures:
   - python: "3.7-dev"

install:
  - travis_retry pip install -U tox-travis

script:
  - tox

after_success:
  - travis_retry pip install -U codecov
  - codecov
